SHOPFRONT-7692 Gift Card - Prevent Internal Gift Cards being sold for…
onshopfront/shopfront-embedded-bridge pull request #1
Opened 2024-11-22 07:14 UTC by RioShopfront

… a card range

2024-11-28 23:54 UTC, g4ther requested changes

2024-11-28 23:54 UTC, g4ther commented on src/Application.ts
> +import {GiftCardCodeCheck} from "./Events/GiftCardCodeCheck";
Nit: Add spaces around

2024-11-28 23:54 UTC, g4ther commented on src/Application.ts
> +        GIFT_CARD_CODE_CHECK    : new Map(),
Nit: Align

2024-11-28 23:54 UTC, g4ther commented on src/ApplicationEvents.ts
> +import {GiftCardCodeCheck} from "./Events/GiftCardCodeCheck";
Nit: Space around

2024-11-28 23:54 UTC, g4ther commented on src/ApplicationEvents.ts
> +        application: string
Do we need this `application` to be sent back?

2024-12-05 03:26 UTC, RioShopfront commented on src/ApplicationEvents.ts
> +        application: string
Not anymore as this information should be written in the error message returned.

2024-12-10 20:36 UTC, g4ther approved these changes

2025-01-15 00:03 UTC, merged